/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        secondary: '#505f76',
        'on-background': '#191c1e',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        outline: '#737784',
        surface: '#f7f9fb',
        'inverse-surface': '#2d3133',
        background: '#f7f9fb',
        'tertiary-fixed-dim': '#4edea3',
        'surface-container-highest': '#e0e3e5',
        'on-primary-fixed': '#001945',
        'outline-variant': '#c3c6d5',
        'on-tertiary-fixed-variant': '#005236',
        'primary-fixed': '#d9e2ff',
        'on-error': '#ffffff',
        'inverse-primary': '#b0c6ff',
        'primary-fixed-dim': '#b0c6ff',
        'secondary-container': '#d0e1fb',
        primary: '#003c90',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#002113',
        'primary-container': '#0f52ba',
        'surface-dim': '#d8dadc',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#d3e4fe',
        'tertiary-fixed': '#6ffbbe',
        'on-secondary-fixed-variant': '#38485d',
        'on-surface': '#191c1e',
        'on-primary-container': '#bcceff',
        'surface-bright': '#f7f9fb',
        'secondary-fixed-dim': '#b7c8e1',
        tertiary: '#004b31',
        'on-secondary-container': '#54647a',
        'surface-container': '#eceef0',
        'on-primary-fixed-variant': '#00419c',
        'surface-variant': '#e0e3e5',
        'error-container': '#ffdad6',
        'tertiary-container': '#006544',
        'on-surface-variant': '#434653',
        'surface-tint': '#1d59c1',
        'on-tertiary-container': '#58e7ab',
        'surface-container-high': '#e6e8ea',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#0b1c30',
        'inverse-on-surface': '#eff1f3',
        'surface-container-low': '#f2f4f6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        lg: '24px',
        sm: '8px',
        md: '16px',
        xs: '4px',
        xl: '32px',
        'container-margin': '24px',
        gutter: '16px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'display-lg': ['Manrope', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'data-mono': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
